version: '3.8'

services:

  backend:
    build: ./backend
    container_name: dell-backend
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: dell-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    restart: unless-stopped
